#! /bin/tcsh

# Script to build SDR support

# Mint 21 - Installing from package manager still doesn't work but
#           building from scratch seems ok.
#           See requirements.txt for list of packages tried.  This
#           led to an "Illegal Instruction" crash so had to build
#           from scratch:
#                       BUILD_Soapy
#                       BUILD_RTL
#                       BUILD_SDRplay

##########################################################################################

# Install building tools
sudo apt update
sudo apt upgrade -y
sudo apt-get -y install build-essential git cmake automake libpulse-dev \
                        libgtk-3-dev freeglut3 freeglut3-dev \
                        python3-dev swig python3-tk \
                        libusb-1.0-0-dev
rehash                        

# Install SoapySDR
if( 1 )then
    echo "\n------------------------------------ Installing SoapySDR ...\n"
    mkdir ~/Dev
    cd ~/Dev

    cmake --help-policy CMP0078
    
    sudo make uninstall SoapySDR
    sudo rm -rf SoapySDR
    git clone https://github.com/pothosware/SoapySDR

    cd SoapySDR
    sudo rm -rf build
    mkdir build
    cd build
    cmake ..
    make

    sudo make install
    sudo ldconfig

    # Permissions were a real problem when trying to get this to
    # work on the RPi.
    sudo chmod -R go+rx /usr/local/lib/SoapySDR
    sudo chmod -R go+rx /usr/local/share/cmake
    rehash
    
    SoapySDRUtil --info

    exit
endif

##########################################################################################

# SoapyRemote - not quite sure what this does or if we need it - probably not
# Its reported to allow sending IQ samples over TCP/IP but need to verify
if( 0 )then
    echo "\n------------------------------------ Install SoapSDR Remote ...\n"
    cd ~/Dev
    sudo rm -rf SoapyRemote
    git clone https://github.com/pothosware/SoapyRemote.git 

    cd SoapyRemote
    rm -rf build
    mkdir build
    cd build
    cmake ../ #-DCMAKE_BUILD_TYPE=Release
    make
    sudo make install
    sudo ldconfig
    exit
endif

