#! /bin/tcsh

# Script to start dual band monitoring of FT8 and, optionally, FT4.

# WSJTX Settings:
#       SDR1  - localhost:4575,  monitor for aloop_0, udp port 2238
#       SDR2  - localhost:4576,  monitor for aloop_1, udp port 2239
#       SDR14 - localhost:4577,  monitor for aloop_2, udp port TBD
#       SDR24 - localhost:4578,  monitor for aloop_3, udp port TBD

###############################################################################

# Set rig to HAMLIB if want to compare decodes from SDR and rig
#set RIG="-rig HAMLIB"
set RIG="-rig NONE"

set FRQS = "1840 3573 7074 10136 14074 18100 21074 24915 28075 50313"
set FRQS = "3573 7074 10136 14074"
set FRQS = "7074 10136 14074 18100"
set FRQS = "1840 3573 7074 10136"

set FRQS = "3573 7074 10136 14074"
set FRQS = "10136 14074 18100 21074"
set FRQS = "10136 14074"
set FRQS = "14074 18100"
#set FRQS = ""

set HOP_TIME=150
#set HOP_TIME=30

set RTL="-rtlhf"
set RTL=""

set LOOPBACK="-loopback"
#set LOOPBACK=""

set FS=5

# Turn this on to monitor FT4 sub-bands also
set FT4=""
#set FT4="-ft4"
#set FT4="-ft44"

set HOPPER="$FT4 -hop -hop_time $HOP_TIME"
set HOPPER="$FT4"

set SDR_OPTS="-vid_bw 45"

###############################################################################

cd ~/Python/pySDR
set PY_SDR = "pySDR.py"

start_loopback

pkill pySDR
pkill bandmap
pkill rigctld

echo Starting pySDR ...
set cmd="$PY_SDR $RTL -fc $FRQS -fs $FS -IF 0 -foffset 0 -mode USB -fsout 48 -af_bw 4 $HOPPER $LOOPBACK $RIG $SDR_OPTS"
echo $cmd
echo $cmd >& /tmp/SDR 
$cmd >>& /tmp/SDR &
#exit

sleep 1
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo Waiting for SDR to start up ...
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
set id=`find_windows "pySDR" 20`

###############################################################################

# Sometimes we need to use pavucontrol to direct audio to right place
echo Starting WSJT-X ...
wsjtx -r SDR1 &
sleep 1
wsjtx -r SDR2 &
sleep 1
if( "$FT4" != "" )then
    wsjtx -r SDR14 &
    sleep 1
    wsjtx -r SDR24 &
    sleep 1
endif

###############################################################################

echo Starting BANDMAPS ...
rm /tmp/BANDMAP*
cd ~/Python/bandmap
set BANDMAP=~/Python/bandmap/bandmap.py
set cmd="$BANDMAP -rig NONE -wsjt SDR1 2238 -dx"
echo $cmd >& /tmp/BANDMAP1 &
$cmd >>& /tmp/BANDMAP1 &
sleep 1

set cmd="$BANDMAP -rig NONE -wsjt SDR2 2239 -dx"
echo $cmd >& /tmp/BANDMAP2 &
$cmd >>& /tmp/BANDMAP2 &
sleep 1

if( "$FT4" != "" )then
    $BANDMAP -rig NONE -wsjt SDR14 -dx >& /tmp/BANDMAP14 &
    sleep 1
    $BANDMAP -rig NONE -wsjt SDR24 -dx >& /tmp/BANDMAP24 &
    sleep 1
endif

###############################################################################

# Organize windows
echo Waiting for bandmaps to start...
while( $#id<3 )
    set id=`find_windows "Band Map" 10`
    sleep 1
end
organize_windows
