#! /bin/tcsh

# Script to make SDR follow rig on adjacent bands - very similar to FT8tri
# This doesn't work quite right on 80m bx of filtering in rig - ugh!

cd ~/Python/pySDR
set PY_SDR = "pySDR.py"

# We need three freqs to set up 3 receivers
set FRQS = "10136 14074 18100"

set RTL="-rtlhf"
set RTL=""

set LOOPBACK="-loopback"
#set LOOPBACK=""

set FS=8

# This is the main difference from FT8tri - select RF out from rig and follow the rig
set HOPPER='-ant B -follow'
#set HOPPER=""

start_loopback

pkill pySDR
#pkill bandmap
#pkill rigctld

# Testing to look at RF spectrum
$PY_SDR -fc 3573 -fs 8 -IF 0 -mode USB -af_bw 4 $HOPPER &
exit

$PY_SDR $RTL -fc $FRQS -fs $FS -IF 0 -mode USB -fsout 48 -af_bw 4 $HOPPER $LOOPBACK &

#exit
sleep 5

# Sometimes we need to use pavucontrol to direct audio to right place
wsjtx -r SDR1 &
sleep 1
wsjtx -r SDR2 &
sleep 1
wsjtx -r SDR3 &

#exit
sleep 5

cd ~/Python/bandmap
set BANDMAP=~/Python/bandmap/bandmap.py
#$BANDMAP -rig NONE -server WSJT3 -dx &
$BANDMAP -rig NONE -wsjt SDR1 -dx &
sleep 1
#$BANDMAP -rig NONE -server WSJT4 -dx &
$BANDMAP -rig NONE -wsjt SDR2 -dx &
sleep 1
#$BANDMAP -rig NONE -server WSJT4 -dx &
$BANDMAP -rig NONE -wsjt SDR3 -dx &

