#! /usr/bin/tcsh

# Script to startup everything for a CW contest

set MODEL = 129

set MASTER="-master"
set PRACTICE=""
set HINTS=""
#set RIG="FLDIGI"
set RIG="HAMLIB -port 4575"

# Settings for NCCC CW Sprints
#set CONTEST="-sprint"
#set WPM=25

# Setting for NAQP
set CONTEST="-naqp"
set WPM=22

# Setting for ARRL DX
#set CONTEST="-arrl_dx"

# Setting for CW Ops mini tests
set CONTEST="-CWops"
set WPM=25
set HINTS="-nohints"

set DEVICE="/dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_AH046H3M120067-if00-port0"

# Kill stale stuff
pkill rigctld
pkill bandmap
pkill wclock

cd ~/Python/pySDR
start_loopback
echo RIG==============$RIG

set FS=48
set LOOPBACK="-loopback -follow_freq"
set PY_SDR = "~/Python/pySDR/pySDR.py"
$PY_SDR -mode IQ -fsout $FS -af_bw 45 -vid_bw 45 -ant B -pan -pan_bw 10 $LOOPBACK -rig DIRECT &
sleep 3

cd ~/Python/pyKeyer
echo pyKeyer.py -wpm ${WPM} $PRACTICE ${CONTEST} -rig $RIG $MASTER $HINTS
pyKeyer.py -wpm ${WPM} $PRACTICE ${CONTEST} -rig $RIG $MASTER $HINTS >& /tmp/KEYER &

